/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import 'stencil-form';


export namespace Components {

  interface DemoApp {}
  interface DemoAppAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'DemoApp': Components.DemoApp;
  }

  interface StencilIntrinsicElements {
    'demo-app': Components.DemoAppAttributes;
  }


  interface HTMLDemoAppElement extends Components.DemoApp, HTMLStencilElement {}
  var HTMLDemoAppElement: {
    prototype: HTMLDemoAppElement;
    new (): HTMLDemoAppElement;
  };

  interface HTMLElementTagNameMap {
    'demo-app': HTMLDemoAppElement
  }

  interface ElementTagNameMap {
    'demo-app': HTMLDemoAppElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
