/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  FormRenderProps,
  FormValidator,
  FormValues,
  StencilFormEventDetail,
} from './declarations';

export namespace Components {
  interface StencilForm {
    'initialValues': FormValues;
    /**
    * Tell Form if initial form values are valid or not on first render
    */
    'isInitialValid'?: boolean;
    'renderer': (props: FormRenderProps<any>) => any;
    'validate': FormValidator<FormValues>;
    /**
    * Tells Form to validate the form on each input's onBlur event
    */
    'validateOnBlur'?: boolean;
    /**
    * Tells Form to validate the form on each input's onInput event
    */
    'validateOnInput'?: boolean;
  }
}

declare global {


  interface HTMLStencilFormElement extends Components.StencilForm, HTMLStencilElement {}
  var HTMLStencilFormElement: {
    prototype: HTMLStencilFormElement;
    new (): HTMLStencilFormElement;
  };
  interface HTMLElementTagNameMap {
    'stencil-form': HTMLStencilFormElement;
  }
}

declare namespace LocalJSX {
  interface StencilForm {
    'initialValues'?: FormValues;
    /**
    * Tell Form if initial form values are valid or not on first render
    */
    'isInitialValid'?: boolean;
    'onSubmit'?: (event: CustomEvent<StencilFormEventDetail>) => void;
    'renderer'?: (props: FormRenderProps<any>) => any;
    'validate'?: FormValidator<FormValues>;
    /**
    * Tells Form to validate the form on each input's onBlur event
    */
    'validateOnBlur'?: boolean;
    /**
    * Tells Form to validate the form on each input's onInput event
    */
    'validateOnInput'?: boolean;
  }

  interface IntrinsicElements {
    'stencil-form': StencilForm;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'stencil-form': LocalJSX.StencilForm & JSXBase.HTMLAttributes<HTMLStencilFormElement>;
    }
  }
}


